// ==========================================================================
// defineAbioticKinetics.hh  --  First-order decay: A -> Product
//
// Generated by CompLaB Studio
//   C[0] = Reactant, C[1] = Product; rate = k * [A]
// ==========================================================================
#ifndef DEFINE_ABIOTIC_KINETICS_HH
#define DEFINE_ABIOTIC_KINETICS_HH

#include <vector>
#include <cmath>
#include <algorithm>
#include <iostream>
#include <iomanip>

namespace AbioticParams {
    constexpr double k_decay     = 1.0e-5;   // [1/s]
    constexpr double MIN_CONC    = 1.0e-20;
    constexpr double MAX_FRAC    = 0.5;
    constexpr double dt_kinetics = 0.0075;    // [s]
}

// ============================================================================
// ABIOTIC KINETICS STATISTICS
// ============================================================================
namespace AbioticKineticsStats {
    static double iter_total_reaction = 0.0;
    static long iter_cells_reacting = 0;
    static long iter_total_calls = 0;

    inline void resetIteration() {
        iter_total_reaction = 0.0;
        iter_cells_reacting = 0;
        iter_total_calls = 0;
    }

    inline void accumulate(double total_rate) {
        iter_total_calls++;
        if (std::abs(total_rate) > 1e-20) {
            iter_cells_reacting++;
            iter_total_reaction += total_rate;
        }
    }
}

void defineAbioticRxnKinetics(
    std::vector<double> C,
    std::vector<double>& subsR,
    plb::plint mask)
{
    using namespace AbioticParams;
    for (size_t i = 0; i < subsR.size(); ++i) subsR[i] = 0.0;

    if (C.size() < 2 || subsR.size() < 2) return;

    double A = std::max(C[0], 0.0);
    if (A < MIN_CONC) return;

    double rate = k_decay * A;
    double max_rate = A * MAX_FRAC / dt_kinetics;
    if (rate > max_rate) rate = max_rate;

    subsR[0] = -rate;   // Reactant consumed
    subsR[1] =  rate;   // Product formed
    AbioticKineticsStats::accumulate(-rate);
}

#endif
