// ==========================================================================
// defineKinetics.hh  --  No-op stub (biotic kinetics not used)
//
// Generated by CompLaB Studio.  This project uses abiotic kinetics only.
// The solver #includes this file unconditionally, so it must exist and
// compile even though it is never called at runtime.
//
// IMPORTANT: Recompile after editing:
//     cd build && cmake .. && make -j$(nproc)
// ==========================================================================
#ifndef DEFINE_KINETICS_HH
#define DEFINE_KINETICS_HH

#include <vector>
#include <cmath>
#include <algorithm>
#include <iostream>
#include <iomanip>

namespace KineticParams {
    constexpr double MIN_BIO = 0.1;
}

// ============================================================================
// DEBUG STATISTICS ACCUMULATOR (required by C++ solver)
// ============================================================================
namespace KineticsStats {
    static double iter_sum_dB = 0.0;
    static double iter_sum_dDOC = 0.0;
    static double iter_max_biomass = 0.0;
    static double iter_max_dB = 0.0;
    static double iter_min_DOC = 1e30;
    static long iter_cells_with_biomass = 0;
    static long iter_cells_with_growth = 0;
    static long iter_total_calls = 0;
    static long iter_cells_limited = 0;

    inline void resetIteration() {
        iter_sum_dB = 0.0;
        iter_sum_dDOC = 0.0;
        iter_max_biomass = 0.0;
        iter_max_dB = 0.0;
        iter_min_DOC = 1e30;
        iter_cells_with_biomass = 0;
        iter_cells_with_growth = 0;
        iter_total_calls = 0;
        iter_cells_limited = 0;
    }

    inline void accumulate(double biomass, double DOC,
                           double dB_dt, double dDOC_dt,
                           bool was_limited) {
        iter_total_calls++;
        if (biomass > 0.1) {
            iter_cells_with_biomass++;
            iter_sum_dB += dB_dt;
            iter_sum_dDOC += dDOC_dt;
            if (biomass > iter_max_biomass) iter_max_biomass = biomass;
            if (dB_dt > iter_max_dB) iter_max_dB = dB_dt;
            if (DOC < iter_min_DOC && DOC > 0) iter_min_DOC = DOC;
            if (dB_dt > 0) iter_cells_with_growth++;
            if (was_limited) iter_cells_limited++;
        }
    }

    inline void accumulate(double biomass, double DOC,
                           double dB_dt, double dDOC_dt) {
        accumulate(biomass, DOC, dB_dt, dDOC_dt, false);
    }

    inline void getStats(long& cells_biomass, long& cells_growth,
                         double& sum_dB, double& max_B,
                         double& max_dB, double& min_DOC) {
        cells_biomass = iter_cells_with_biomass;
        cells_growth = iter_cells_with_growth;
        sum_dB = iter_sum_dB;
        max_B = iter_max_biomass;
        max_dB = iter_max_dB;
        min_DOC = (iter_min_DOC < 1e20) ? iter_min_DOC : 0.0;
    }

    inline long getLimitedCells() { return iter_cells_limited; }
}

void defineRxnKinetics(
    std::vector<double> B,
    std::vector<double> C,
    std::vector<double>& subsR,
    std::vector<double>& bioR,
    plb::plint mask)
{
    // No-op: biotic kinetics not used in this template
    for (auto& r : subsR) r = 0.0;
    for (auto& r : bioR)  r = 0.0;
}

#endif
