// ==========================================================================
// defineAbioticKinetics.hh  --  First-order decay: Reactant -> Product
//
// Generated by CompLaB Studio for template: Abiotic - First Order Decay
//
// Substrates: 2  (index 0 = Reactant, index 1 = Product)
//
// IMPORTANT: Recompile after editing:
//     cd build && cmake .. && make -j$(nproc)
// ==========================================================================
#ifndef DEFINE_ABIOTIC_KINETICS_HH
#define DEFINE_ABIOTIC_KINETICS_HH

#include <vector>
#include <cmath>
#include <algorithm>
#include <iostream>
#include <iomanip>

namespace AbioticParams {
    constexpr double k_decay = 1.0e-5;     // [1/s] first-order rate constant
    constexpr double MIN_CONC = 1.0e-20;
    constexpr double MAX_RATE_FRACTION = 0.5;
    constexpr double dt_kinetics = 0.0075;  // [s] kinetics timestep
}

// ============================================================================
// ABIOTIC KINETICS STATISTICS
// ============================================================================
namespace AbioticKineticsStats {
    static double iter_total_reaction = 0.0;
    static long iter_cells_reacting = 0;
    static long iter_total_calls = 0;

    inline void resetIteration() {
        iter_total_reaction = 0.0;
        iter_cells_reacting = 0;
        iter_total_calls = 0;
    }

    inline void accumulate(double total_rate) {
        iter_total_calls++;
        if (std::abs(total_rate) > 1e-20) {
            iter_cells_reacting++;
            iter_total_reaction += total_rate;
        }
    }
}

void defineAbioticRxnKinetics(
        std::vector<double> C,
        std::vector<double>& subsR,
        plb::plint mask)
{
    using namespace AbioticParams;

    for (auto& r : subsR) r = 0.0;

    if (C.size() < 2) return;

    // First-order decay: dC/dt = -k * C
    double rate = k_decay * std::max(C[0], 0.0);

    // Clamp so we don't consume more than MAX_RATE_FRACTION per timestep
    double max_rate = C[0] * MAX_RATE_FRACTION / dt_kinetics;
    if (rate > max_rate) rate = max_rate;

    subsR[0] = -rate;   // Reactant consumed
    subsR[1] =  rate;   // Product formed

    AbioticKineticsStats::accumulate(-rate);
}

#endif
