// ==========================================================================
// defineAbioticKinetics.hh  --  No-op stub (abiotic kinetics not used)
//
// Generated by CompLaB Studio.  This project uses biotic kinetics only.
// The solver #includes this file unconditionally, so it must exist and
// compile even though it is never called at runtime.
// ==========================================================================
#ifndef DEFINE_ABIOTIC_KINETICS_HH
#define DEFINE_ABIOTIC_KINETICS_HH

#include <vector>
#include <cmath>
#include <algorithm>
#include <iostream>
#include <iomanip>

// ============================================================================
// ABIOTIC KINETICS STATISTICS
// ============================================================================
namespace AbioticKineticsStats {
    static double iter_total_reaction = 0.0;
    static long iter_cells_reacting = 0;
    static long iter_total_calls = 0;

    inline void resetIteration() {
        iter_total_reaction = 0.0;
        iter_cells_reacting = 0;
        iter_total_calls = 0;
    }

    inline void accumulate(double total_rate) {
        iter_total_calls++;
        if (std::abs(total_rate) > 1e-20) {
            iter_cells_reacting++;
            iter_total_reaction += total_rate;
        }
    }
}

void defineAbioticRxnKinetics(
    std::vector<double> C,
    std::vector<double>& subsR,
    plb::plint mask)
{
    for (size_t i = 0; i < subsR.size(); ++i) subsR[i] = 0.0;
}

#endif
